<?php

add_action( 'plugins_loaded', 'animalsfastdezineplugin_register_acf_cavalo' );
function animalsfastdezineplugin_register_acf_cavalo(){
    if( function_exists('register_field_group') ):   
        
        $camposHorses = array(
            'key' => 'group_55a956e775039',
            'title' => __('Horse Fields', 'animalsfastdezineplugin'),
            'fields' => array(
                array(
                    'key' => 'field_55a956e79022d',
                    'label' => __('INFORMATION', 'animalsfastdezineplugin'),
                    'name' => 'identificação',
                    'prefix' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_55a956e7903cb',
                    'label' => __('Gender', 'animalsfastdezineplugin'),
                    'name' => 'gender',
                    'prefix' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => 33.3333,
                        'class' => 'campo-importado campos-our_horses',
                        'id' => '',
                    ),
                    'choices' => array(
                        '-' => '-',
                        'Potro' => __('Colt', 'animalsfastdezineplugin'),
                        'Garanhão' => __('Horse/Stallion', 'animalsfastdezineplugin'),
                        'Potra' => __('Filly', 'animalsfastdezineplugin'),
                        'Égua' => __('Mare', 'animalsfastdezineplugin'),
                        'Castrado' => __('Gelding', 'animalsfastdezineplugin'),
                    ),
                    'default_value' => array(
                        '' => '',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array(
                    'key' => 'field_55a956e790458',
                    'label' => __('Birth Date', 'animalsfastdezineplugin'),
                    'name' => 'date_birth',
                    'prefix' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => 33.3333,
                        'class' => 'campo-importado',
                        'id' => '',
                    ),
                    'display_format' => 'd/m/Y',
                    'return_format' => 'd/m/Y',
                    'first_day' => 1,
                ),
                array(
                    'key' => 'field_55a956e7906f8',
                    'label' => __('Color', 'animalsfastdezineplugin'),
                    'name' => 'color',
                    'prefix' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => 33.3333,
                        'class' => 'campo-importado',
                        'id' => '',
                    ),
                    'choices' => array(
                        '-' => '-',
                        'ALAZÃ' => 'ALAZÃ',
                        'ALAZÃ AMARILHA' => 'ALAZÃ AMARILHA',
                        'ALAZÃ AMARILHA P/ TORDILHA' => 'ALAZÃ AMARILHA P/ TORDILHA',
                        'ALAZÃ AMARILHA PAMPA' => 'ALAZÃ AMARILHA PAMPA',
                        'ALAZÃ AMARILHA PAMPA P/ TORDILHA PAMPA' => 'ALAZÃ AMARILHA PAMPA P/ TORDILHA PAMPA',
                        'ALAZÃ P/ ROSILHA' => 'ALAZÃ P/ ROSILHA',
                        'ALAZÃ P/ TORDILHA' => 'ALAZÃ P/ TORDILHA',
                        'ALAZÃ PAMPA' => 'ALAZÃ PAMPA',
                        'ALAZÃ PAMPA P/ TORDILHA PAMPA' => 'ALAZÃ PAMPA P/ TORDILHA PAMPA',
                        'ALAZÃ SOBRE BAIA' => 'ALAZÃ SOBRE BAIA',
                        'ALAZÃ SOBRE BAIA P/ TORDILHA' => 'ALAZÃ SOBRE BAIA P/ TORDILHA',
                        'ALAZÃ SOBRE BAIA PAMPA' => 'ALAZÃ SOBRE BAIA PAMPA',
                        'ALAZÃ SOBRE BAIA PAMPA P/ TORDILHA PAMPA' => 'ALAZÃ SOBRE BAIA PAMPA P/ TORDILHA PAMPA',
                        'BAIA' => 'BAIA',
                        'BAIA P/ ROSILHA' => 'BAIA P/ ROSILHA',
                        'BAIA P/ TORDILHA' => 'BAIA P/ TORDILHA',
                        'BAIA PAMPA' => 'BAIA PAMPA',
                        'BAIA PAMPA P/ TORDILHA PAMPA' => 'BAIA PAMPA P/ TORDILHA PAMPA',
                        'CASTANHA' => 'CASTANHA',
                        'CASTANHA P/ TORDILHA' => 'CASTANHA P/ TORDILHA',
                        'CASTANHA P/ ROSILHA' => 'CASTANHA P/ ROSILHA',
                        'CASTANHA PAMPA' => 'CASTANHA PAMPA',
                        'CASTANHA PAMPA P/ TORDILHA PAMPA' => 'CASTANHA PAMPA P/ TORDILHA PAMPA',
                        'LOBUNA' => 'LOBUNA',
                        'LOBUNA P/ TORDILHA' => 'LOBUNA P/ TORDILHA',
                        'LOBUNA PAMPA' => 'LOBUNA PAMPA',
                        'LOBUNA PAMPA P/ TORDILHA PAMPA' => 'LOBUNA PAMPA P/ TORDILHA PAMPA',
                        'PAMPA DE ALAZÃ' => 'PAMPA DE ALAZÃ',
                        'PAMPA DE ALAZÃ AMARILHA' => 'PAMPA DE ALAZÃ AMARILHA',
                        'PAMPA DE ALAZÃ AMARILHA P/ PAMPA TORDILHA' => 'PAMPA DE ALAZÃ AMARILHA P/ PAMPA TORDILHA',
                        'PAMPA DE ALAZÃ P/ PAMPA DE TORDILHA' => 'PAMPA DE ALAZÃ P/ PAMPA DE TORDILHA',
                        'PAMPA DE ALAZÃ SOBRE BAIA' => 'PAMPA DE ALAZÃ SOBRE BAIA',
                        'PAMPA DE ALAZÃ SOBRE BAIA P/ PAMPA DE TORDILHA' => 'PAMPA DE ALAZÃ SOBRE BAIA P/ PAMPA DE TORDILHA',
                        'PAMPA DE BAIA' => 'PAMPA DE BAIA',
                        'PAMPA DE BAIA P/ PAMPA DE TORDILHA' => 'PAMPA DE BAIA P/ PAMPA DE TORDILHA',
                        'PAMPA DE CASTANHA' => 'PAMPA DE CASTANHA',
                        'PAMPA DE CASTANHA P/ PAMPA TORDILHA' => 'PAMPA DE CASTANHA P/ PAMPA TORDILHA',
                        'PAMPA DE LOBUNA' => 'PAMPA DE LOBUNA',
                        'PAMPA DE LOBUNA P/ PAMPA DE TORDILHA' => 'PAMPA DE LOBUNA P/ PAMPA DE TORDILHA',
                        'PAMPA DE PRETA' => 'PAMPA DE PRETA',
                        'PAMPA DE PRETA P/ PAMPA DE TORDILHA' => 'PAMPA DE PRETA P/ PAMPA DE TORDILHA',
                        'PAMPA DE ROSILHA' => 'PAMPA DE ROSILHA',
                        'PAMPA DE ROSILHA P/ PAMPA DE TORDILHA' => 'PAMPA DE ROSILHA P/ PAMPA DE TORDILHA',
                        'PAMPA DE TORDILHA' => 'PAMPA DE TORDILHA',
                        'PRETA' => 'PRETA',
                        'PRETA P/ ROSILHA' => 'PRETA P/ ROSILHA',
                        'PRETA P/ TORDILHA' => 'PRETA P/ TORDILHA',
                        'PRETA PAMPA' => 'PRETA PAMPA',
                        'PRETA PAMPA P/ TORDILHA PAMPA' => 'PRETA PAMPA P/ TORDILHA PAMPA',
                        'ROSILHA' => 'ROSILHA',
                        'ROSILHA P/ TORDILHA' => 'ROSILHA P/ TORDILHA',
                        'ROSILHA PAMPA' => 'ROSILHA PAMPA',
                        'ROSILHA PAMPA P/ TORDILHA PAMPA' => 'ROSILHA PAMPA P/ TORDILHA PAMPA',
                        'TORDILHA' => 'TORDILHA',
                        'TORDILHA PAMPA' => 'TORDILHA PAMPA',
                    ),
                    'default_value' => array(
                        '' => '',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array (
                    'key' => 'field_55de2245ca0f8',
                    'label' => __('Association Number', 'animalsfastdezineplugin'),
                    'name' => 'association_number',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => 25,
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => 'field_55a956e790914',
                    'label' => __('Chip No.', 'animalsfastdezineplugin'),
                    'name' => 'chip',
                    'prefix' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => 25,
                        'class' => 'campo-importado',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => 'field_55a956e79099a',
                    'label' => __('Book', 'animalsfastdezineplugin'),
                    'name' => 'book',
                    'prefix' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => 25,
                        'class' => 'campo-importado',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => 'field_55a956e790a21',
                    'label' => __('DNA Exam', 'animalsfastdezineplugin'),
                    'name' => 'dna_exam',
                    'prefix' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => 25,
                        'class' => 'campo-importado',
                        'id' => '',
                    ),
                    'choices' => array(
                        '-' => '-',
                        'Sim' => __('Yes', 'animalsfastdezineplugin'),
                        'Não' => __('No', 'animalsfastdezineplugin'),
                    ),
                    'default_value' => array(
                        '' => '',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array(
                    'key' => 'field_55a956e7916e3',
                    'label' => __('Type of Gait', 'animalsfastdezineplugin'),
                    'name' => 'type_of_gait',
                    'prefix' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => 'campos-our_horses',
                        'id' => '',
                    ),
                    'choices' => array(
                        '-' => '-',
                        'Batida' => __('Hit', 'animalsfastdezineplugin'),
                        'Picada' => __('Chopped', 'animalsfastdezineplugin'),
                    ),
                    'default_value' => array(
                        '' => '',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array(
                    'key' => 'field_55a956e790566',
                    'label' => __('Height (hands)', 'animalsfastdezineplugin'),
                    'name' => 'height',
                    'prefix' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => 25,
                        'class' => 'only-number',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => 'field_55a956e79176c',
                    'label' => __('Animal Use', 'animalsfastdezineplugin'),
                    'name' => 'use',
                    'prefix' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => 'campos-our_horses',
                        'id' => '',
                    ),
                    'choices' => array(
                        '-' => '-',
                        'Cavalgada' => __('Cavalcade', 'animalsfastdezineplugin'),
                        'Passeio' => __('Ride', 'animalsfastdezineplugin'),
                        'Lida na fazenda/gado' => __('Work on farm/cattle', 'animalsfastdezineplugin'),
                        'Concurso de marcha' => __('Marching contest', 'animalsfastdezineplugin'),
                        'Exposições da raça' => __('Breed exposition', 'animalsfastdezineplugin'),
                        'Enduro' => __('Enduro', 'animalsfastdezineplugin'),
                        'Equitação' => __('Horsemanship', 'animalsfastdezineplugin'),
                        'Reprodução' => __('Reproduction', 'animalsfastdezineplugin'),
                    ),
                    'default_value' => array(
                        '' => '',
                    ),
                    'allow_null' => 0,
                    'multiple' => 1,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array(
                    'key' => 'field_55a956e791659',
                    'label' => __('Temperament', 'animalsfastdezineplugin'),
                    'name' => 'temperament',
                    'prefix' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        '-' => '-',
                        1 => __('Calmer', 'animalsfastdezineplugin'),
                        2 => __('Calm', 'animalsfastdezineplugin'),
                        3 => __('Racial standard', 'animalsfastdezineplugin'),
                        4 => __('Angry', 'animalsfastdezineplugin'),
                        5 => __('Angrier', 'animalsfastdezineplugin'),
                    ),
                    'default_value' => array(
                        '' => '',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'disabled' => 0,
                    'readonly' => 0,
                ),
                array(
                    'key' => 'field_55a956e79239d',
                    'label' => __('Categories', 'animalsfastdezineplugin'),
                    'name' => 'categories',
                    'prefix' => '',
                    'type' => 'taxonomy',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33.3333',
                        'class' => 'select-full campos-our_horses',
                        'id' => '',
                    ),
                    'taxonomy' => 'cavalo_categoria',
                    'field_type' => 'checkbox',
                    'allow_null' => 0,
                    'load_save_terms' => 1,
                    'return_format' => 'id',
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_25cad4b47e5cb',
                    'label' => __('Show ribbon from', 'animalsfastdezineplugin'),
                    'name' => 'show_ribbon',
                    'prefix' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '33.3333',
                        'class' => 'select-full',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'selo',
                    ),
                    'taxonomy' => '',
                    'field_type' => 'select',
                    'allow_null' => 1,
                    'load_save_terms' => 0,
                    'return_format' => 'id',
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_55de07127fd8c',
                    'label' => __('Ribbon side', 'animalsfastdezineplugin'),
                    'name' => 'ribbon_side',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '33.3333',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        'left' => __('Left', 'animalsfastdezineplugin'),
                        'right' => __('Right', 'animalsfastdezineplugin'),
                    ),
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => 'left',
                    'layout' => 'vertical',
                ),
                array(
                    'key' => 'field_55a956F58022d',
                    'label' => __('DESCRIPTION', 'animalsfastdezineplugin'),
                    'name' => '',
                    'prefix' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_55a956e79AA01',
                    'label' => __('Animal Text', 'animalsfastdezineplugin'),
                    'name' => 'description',
                    'prefix' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => 'wpautop',
                    'readonly' => 0,
                    'disabled' => 0,
                ),                
                array(
                    'key' => 'field_55a956e790aa8',
                    'label' => __('BREEDER/OWNER(S)', 'animalsfastdezineplugin'),
                    'name' => 'criador',
                    'prefix' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_55aae750486ce',
                    'label' => __('Breeder', 'animalsfastdezineplugin'),
                    'name' => 'breeder',
                    'prefix' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'campo-importado',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'criador',
                    ),
                    'taxonomy' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'object',
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_55aae761486cf',
                    'label' => __('Owner', 'animalsfastdezineplugin'),
                    'name' => 'owner',
                    'prefix' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => 'campo-importado',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'criador',
                    ),
                    'taxonomy' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'object',
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_55c3a732d6a58',
                    'label' => __('Owner percentage', 'animalsfastdezineplugin'),
                    'name' => 'owner_percent',
                    'prefix' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => 'field_55a956e7913ad',
                    'label' => __('AWARDS', 'animalsfastdezineplugin'),
                    'name' => 'awards',
                    'prefix' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_55a956e79143b',
                    'label' => '',
                    'name' => 'content_awards',
                    'prefix' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'min' => '',
                    'max' => '',
                    'layout' => 'table',
                    'button_label' => __('Add', 'animalsfastdezineplugin'),
                    'sub_fields' => array(
                        array(
                            'key' => 'field_55c3b356d6a59',
                            'label' => __('Display on site', 'animalsfastdezineplugin'),
                            'name' => 'view_site',
                            'prefix' => '',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                        ),
                        array(
                            'key' => 'field_55a956e82404a',
                            'label' => __('Event', 'animalsfastdezineplugin'),
                            'name' => 'event_awards',
                            'prefix' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'acf-disabled',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55a956e8240c3',
                            'label' => __('City', 'animalsfastdezineplugin'),
                            'name' => 'city_awards',
                            'prefix' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'acf-disabled',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55a956e824121',
                            'label' => __('Date', 'animalsfastdezineplugin'),
                            'name' => 'period_awards',
                            'prefix' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'acf-disabled',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55a956e824197',
                            'label' => __('Award', 'animalsfastdezineplugin'),
                            'name' => 'award',
                            'prefix' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'acf-disabled',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55a956e82420c',
                            'label' => __('Number of participating animals', 'animalsfastdezineplugin'),
                            'name' => 'number_of_partipating_animals_award',
                            'prefix' => '',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'acf-disabled',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_55a956e79187b',
                    'label' => __('MEDIA', 'animalsfastdezineplugin'),
                    'name' => 'media',
                    'prefix' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_55a956e791906',
                    'label' => __('Gallery', 'animalsfastdezineplugin'),
                    'name' => 'gallery',
                    'prefix' => '',
                    'type' => 'gallery',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'min' => '',
                    'max' => '',
                    'preview_size' => 'thumbnail',
                    'library' => 'uploadedTo',
                ),
                array (
                    'key' => 'field_55a956e7919F5',
                    'label' => __('Videos', 'animalsfastdezineplugin'),
                    'name' => 'videos',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => 100,
                        'class' => '',
                        'id' => '',
                    ),
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5f7956e199992',
                            'label' => __('Video URL', 'animalsfastdezineplugin'),
                            'name' => 'url',
                            'prefix' => '',
                            'type' => 'url',
                            'instructions' =>  __('Only Youtube video Url. Ex. https://www.youtube.com/watch?v=HjhNlqE5N34', 'animalsfastdezineplugin'),
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        )    
                    ),
                    'min' => '1',
                    'max' => '',
                    'layout' => 'table',
                    'button_label' => __('Add', 'animalsfastdezineplugin'),
                ),                
                array(
                    'key' => 'field_55a956e792422',
                    'label' => __('GENEALOGY', 'animalsfastdezineplugin'),
                    'name' => 'genealogy',
                    'prefix' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                ),
                array(
                    'key' => 'field_55a956e7924a8',
                    'label' => '',
                    'name' => '',
                    'prefix' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'cavalo',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'page_attributes',
                //11 => 'featured_image',
                12 => 'categories',
                13 => 'tags',
                14 => 'send-trackbacks',
            ),
        );
        
        register_field_group($camposHorses);
    
    endif;

    if( function_exists('acf_add_options_page') ) {

        acf_add_options_page(array(
            'page_title' 	=> __('Show this info', 'animalsfastdezineplugin'),
            'menu_title'	=> __('Show info info', 'animalsfastdezineplugin'),
            'menu_slug' 	=> 'show-fields-cavalo',
            'capability'	=> 'edit_posts',
            'redirect'		=> true
        ));
        
    }

    if( function_exists('register_field_group') ):
        
        register_field_group(array (
            'key' => 'group_55cddc5f7ea0c',
            'title' => __('Horse information', 'animalsfastdezineplugin'),
            'fields' => array (
                array (
                    'key' => 'field_55cddc70da53b',
                    'label' => __('Show informations on website', 'animalsfastdezineplugin'),
                    'name' => 'campo_exibir_cavalo',
                    'prefix' => '',
                    'type' => 'checkbox',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array (
                        'gender' => __('Gender', 'animalsfastdezineplugin'),
                        'date_birth' => __('Birth Date', 'animalsfastdezineplugin'),
                        'color' => __('Color', 'animalsfastdezineplugin'),
                        'height' => __('Height (hands)', 'animalsfastdezineplugin'),
                        'associations' => __('Associations', 'animalsfastdezineplugin'),
                        'chip' => __('Chip', 'Chip No.'),
                        'book' => __('Book', 'animalsfastdezineplugin'),
                        'dna_exam' => __('DNA Exam', 'animalsfastdezineplugin'),
                        'type_of_gait' => __('Type of Gait', 'animalsfastdezineplugin'),
                        'use' => __('Animal Use', 'animalsfastdezineplugin'),
                        'temperament' => __('Temperament', 'animalsfastdezineplugin'),
                        'breeder' => __('Breeder', 'animalsfastdezineplugin'),
                        'owner' => __('Owner', 'animalsfastdezineplugin'),
                        'description' => __('Description', 'animalsfastdezineplugin'),
                    ),
                    'default_value' => array (
                        '' => '',
                    ),
                    'layout' => 'vertical',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'show-fields-cavalo',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
        ));

    endif;
}

function getHorseDescription($ID = null){
    
    if(!$ID){
        $ID = get_the_ID();
    }

    return get_field('description', $ID);
    
}

add_action('acf/input/admin_head', 'animalsfastdezineplugin_cavalo_acf_admin_head');
function animalsfastdezineplugin_cavalo_acf_admin_head() {
    ?>
    <script type="text/javascript">
        (function($) {
            $(document).ready(function(){
                if($('.acf-field-55a956e7924a8 .acf-input').length > 0){
                    $('.acf-field-55a956e7924a8 .acf-input').append( $('.plugin-pedigree') );
                }
                //$('#pedigree_horses_box').hide();
            });
        })(jQuery);
    </script>
    <style type="text/css">
        .campo-importado .acf-input {
            border: 1px solid #333333;
            background-color: #999999;
        }
    </style>
<?php

}